---
- name: Verify connection on loadbalancer
  hosts: loadbalancer
  become: true
  tasks:

    # This task curl http://loadbalancer
    # and check if it reaches web1 or web2
    - name: Test loadbalancer nginx is configured with correct html response!
      uri:
        url: http://loadbalancer
        return_content: true
      register: result
      failed_when:
        - "'<title>This is server web1</title>' not in result.content"
        - "'<title>This is server web2</title>' not in result.content"
